"""
Django settings for NanoMonitor project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from enum import Enum
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-st5vc^q#3xx6yompqcje=yp*v_6j9vk7=*!l^ass))z&)b2cf#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['bananode.makes.trade', 'nanode.makes.trade', '127.0.0.1', 'localhost','localhost:8000']

UNSAFE_RPC_ENABLED = False
# RPC NODE SETTINGS
RPC_PORT = "7072"
RPC_HOST = "127.0.0.1"
RPC_URL = f"http://{RPC_HOST}:{RPC_PORT}"
RPC_URL = "https://bananode.makes.trade"

NODE_ACCOUNT = "ban_3pjf6h7o38oi7em7o4615n484xzyc1eat5qsiygtz6oentpoansq1keyrkcx"
# DONATION ADDRESSES
# SEtting to None will remove from footer.
# Ex. BANANO_ADDRESS = "ban_wahteverwalletaddress"
BANANO_ADDRESS ="ban_36fx8aapqpbcm9y8wtzj9pc785k4aozh3t59dzu5pm45mtp3tx8ruh6eohm5"
BANANO_NODE_ADDRESS = "ban_3pjf6h7o38oi7em7o4615n484xzyc1eat5qsiygtz6oentpoansq1keyrkcx"
NANO_ADDRESS = "nano_whateverbsaddress"
KOFI_ADDRESS = None

# OPTIONS NANO BANANO
class Chain(Enum):
    NANO = "Nano"
    BANANO = "Banano"

CHAIN = Chain.BANANO

# tab title
DEFAULT_TAB_TITLE = f"{CHAIN} Status Monitor"
DEFAULT_TITLE = "Makes.Trade "
DEFAULT_SUBTITLE = f"Status Monitor for {CHAIN} blockchain. Check out Https://Makes.Trade for other cool blockchain stuff."

nano_dark = 1
nano_light = 2
banano_dark = 3
banano_light = 4


THEME = nano_light

NANO_SYMBOL_TEXT = "Ӿ"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor.apps.MonitorConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NanoMonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processors. -> sitewide template data.
                'monitor.context_processors.donation_addresses',
                'monitor.context_processors.constants',

            ],
        },
    },
]

WSGI_APPLICATION = 'NanoMonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_files/')]
STATIC_ROOT = "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
